const KEYS=['en','idn','eo','tr','ja'];const META={en:['🇬🇧','English','en-US'],idn:['🇮🇩','Indonesia','id-ID'],eo:['⭐','Esperanto','eo'],tr:['🇹🇷','Türkçe','tr-TR'],ja:['🇯🇵','日本語','ja-JP']};
let words=JSON.parse(localStorage.getItem('polyglotWords')||'null')||structuredClone(STARTER_WORDS);let idx=0,showEx=false;
const $=s=>document.querySelector(s);const save=()=>localStorage.setItem('polyglotWords',JSON.stringify(words));
function speak(text,lang){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;speechSynthesis.speak(u)}
function cats(){let a=['すべて',...new Set(words.map(w=>w.category))];$('#category').innerHTML=a.map(x=>`<option>${x}</option>`).join('')}
function filtered(){let c=$('#category').value;return c==='すべて'?words:words.filter(w=>w.category===c)}
function render(){let a=filtered();if(!a.length)return;idx=Math.min(idx,a.length-1);let w=a[idx];$('#counter').textContent=`${idx+1} / ${a.length} ・ ${w.category}`;$('#card').className='card'+(showEx?' showExamples':'');$('#card').innerHTML=KEYS.map(k=>`<div class="lang"><div class="langHead"><div><div class="label">${META[k][0]} ${META[k][1]}</div><div class="word">${w[k].word}</div></div><button class="speak" data-text="${esc(w[k].word)}" data-lang="${META[k][2]}">🔊</button></div><div class="example">${w[k].example||''} ${w[k].example?`<button class="speak" data-text="${esc(w[k].example)}" data-lang="${META[k][2]}">🔊</button>`:''}</div></div>`).join('');bindSpeak()}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
function bindSpeak(){document.querySelectorAll('.speak').forEach(b=>b.onclick=()=>speak(b.dataset.text,b.dataset.lang))}
function renderList(){let q=$('#search').value.toLowerCase();$('#wordList').innerHTML=words.filter(w=>KEYS.some(k=>(w[k].word+' '+(w[k].example||'')).toLowerCase().includes(q))).map(w=>`<div class="listRow">${KEYS.map(k=>`<div><small>${META[k][0]} ${META[k][1]}</small><b>${w[k].word}</b></div>`).join('')}</div>`).join('')}
function quiz(){let w=words[Math.floor(Math.random()*words.length)];$('#quizBox').dataset.id=w.id;$('#quizBox').innerHTML=`<div class="label">🇯🇵 日本語から4言語を思い出す</div><div class="quizPrompt">${w.ja.word}</div>`}
function quizAns(){let w=words.find(x=>x.id===$('#quizBox').dataset.id);$('#quizBox').innerHTML+=`<div class="quizAns">${KEYS.slice(0,4).map(k=>`${META[k][0]} <b>${w[k].word}</b> <button class="speak" data-text="${esc(w[k].word)}" data-lang="${META[k][2]}">🔊</button>`).join('<br>')}</div>`;bindSpeak()}
function form(){ $('#addForm').innerHTML=`<div class="field">カテゴリー<input name="category" value="基本"></div>`+KEYS.map(k=>`<div class="field">${META[k][0]} ${META[k][1]}<input name="${k}" placeholder="単語・表現"><input name="${k}Ex" placeholder="例文（任意）"></div>`).join('')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='list')renderList();if(b.dataset.view==='quiz')quiz()});
$('#prev').onclick=()=>{let a=filtered();idx=(idx-1+a.length)%a.length;showEx=false;render()};$('#next').onclick=()=>{let a=filtered();idx=(idx+1)%a.length;showEx=false;render()};$('#examples').onclick=()=>{showEx=!showEx;render()};$('#shuffle').onclick=()=>{let a=filtered();idx=Math.floor(Math.random()*a.length);showEx=false;render()};$('#category').onchange=()=>{idx=0;render()};$('#search').oninput=renderList;$('#quizAnswer').onclick=quizAns;$('#quizNext').onclick=quiz;
$('#addWord').onclick=()=>{let f=new FormData($('#addForm'));let w={id:'u'+Date.now(),category:f.get('category')||'追加'};KEYS.forEach(k=>w[k]={word:f.get(k)||'',example:f.get(k+'Ex')||''});if(!w.en.word&&!w.ja.word)return alert('少なくとも英語または日本語を入力してください。');words.push(w);save();cats();render();$('#addForm').reset();alert('追加しました。')};
$('#export').onclick=()=>{let blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),words},null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='5languages-vocabulary.json';a.click();URL.revokeObjectURL(a.href)};
$('#import').onchange=async e=>{try{let j=JSON.parse(await e.target.files[0].text());let x=Array.isArray(j)?j:j.words;if(!Array.isArray(x))throw 0;words=x;save();cats();render();alert('読み込みました。')}catch{alert('JSONを読み込めませんでした。')}};
$('#reset').onclick=()=>{if(confirm('追加データを消して初期状態に戻しますか？')){words=structuredClone(STARTER_WORDS);save();cats();render()}};$('#theme').onclick=()=>document.body.classList.toggle('dark');
cats();form();render();
